// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sopjkezgraqpybidsjdj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNvcGprZXpncmFxcHliaWRzamRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ2NDQzNzAsImV4cCI6MjA5MDIyMDM3MH0.GijjkO5QmvRhf5Lk7aV3FjcpY4CIeAs7iPSHDhKeeLY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});