// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wsyhosbcwskyxrvvzjbq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndzeWhvc2Jjd3NreXhydnZ6amJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODA3OTA3NTUsImV4cCI6MjA5NjM2Njc1NX0.NbBLl_VGQOeYdisVluL1-RkVrd7H8CesBfdc0y2lNQE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});